### ISSUE TITLE
can not run on windows 10

### ISSUE THREAD

**Issue by capqueen** [ForNeVeR/ManagedSpy#15]
I build it in windows 10, but can not run.
exception throw at Commands.cpp line 94.

**Comment by ForNeVeR** [comment]
Could you please provide a stack trace and/or any additional details? I am executing and testing it on Windows 10 and it doesn't seem to have any problems in my experience. But it surely could have them, I'd be happy to help and fix all the bugs.

**Comment by ForNeVeR** [comment]
Please also note what kind of build were you used: x86 or x64, debug or release?

**Comment by capqueen** [comment]
Thanks a lot,it run well after run as administrator.

**Comment by ForNeVeR** [comment]
Yes, that's a known issue: #12. I think we'll do something about it sooner or later.

**Comment by ForNeVeR** [comment]
And, yeah, thank you for your report anyways.
