### ISSUE TITLE
Rearrange output directories

### ISSUE THREAD

**Issue by uian2000** [ForNeVeR/ManagedSpy#20]
The original source directories is simply and clean.
But once be compiled too many bin/release/debug/win32/x86/x64/... directories appears.
Maybe we could make only one bin directory contain them all.
Shell we?

**Comment by ForNeVeR** [comment]
Yes, the current layout looks very strange indeed.

I'll move `ManagedSpyLib` binaries into `ManagedSpyLib/bin` directory (currently they resides in the solution root directory for some reason).
