### ISSUE TITLE
Support both x32 and x64 processes

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/ManagedSpy#3]
The idea is to start some sort of 32-bit proxy process on x64 systems.

**Comment by fuct** [comment]
what needs done to fix this?

**Comment by ForNeVeR** [comment]
@fuct, well, I was thinking about creating two proxy processes for 32-bit and 64-bit communication. The main process then should start them both and talk to them through WCF, Remoting or simply through socket (I think I'd use WCF because I have more experience with it).
