### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by qualityking** [ForNeVeR/ManagedSpy#8]
An unhandled exception of type 'System.BadImageFormatException' occurred in ManagedSpy.exe

Additional information: Could not load file or assembly 'ManagedSpyLib, Version=1.0.3190.24822, Culture=neutral, PublicKeyToken=205864fb3a528ec8' or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Comment by ForNeVeR** [comment]
Sorry, I cannot reproduce this problem. What project configuration have you tried to build? Please note that currently only x86 build is supported.

**Comment by ForNeVeR** [comment]
Both x86 and x64 builds are supported now, and the problem still wasn't noticed, so I'm closing this. Feel free to reopen if you can reproduce it.
